'use client';
import { useEffect, useMemo, useState } from 'react';
type Row = Record<string, any>;
const tabs = ['대시보드','직원관리','휴무관리','근무인원','보건증','인센티브','연결확인'];
function val(r:Row, keys:string[]){ for(const k of keys){ const v=r?.[k]; if(v!==undefined && v!==null && String(v).trim()!=='') return String(v).trim(); } return ''; }
function dateOnly(v:any){ const s=String(v||''); const m=s.match(/\d{4}[.-]\s*\d{1,2}[.-]\s*\d{1,2}|\d{4}-\d{2}-\d{2}/); if(m) return m[0].replace(/\.\s*/g,'-').replace(/\.$/,''); return s.slice(0,10); }
function isActive(r:Row){ const s=val(r,['상태','재직상태','사용여부']); return !s.includes('퇴사') && !s.includes('제외') && !s.includes('비활성'); }
function nameOf(r:Row){ return val(r,['이름','직원명','성명','name']); }
async function api(action='all', params:Row={}){ const url=new URL('/api/masterdb', location.origin); url.searchParams.set('action',action); Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,String(v))); const res=await fetch(url.toString(),{cache:'no-store'}); return res.json(); }
export default function Page(){
 const [tab,setTab]=useState('대시보드'); const [data,setData]=useState<Row>({}); const [loading,setLoading]=useState(false); const [err,setErr]=useState(''); const [month,setMonth]=useState(new Date().toISOString().slice(0,7));
 async function load(){ setLoading(true); setErr(''); try{ const j=await api('all',{month}); if(j.ok===false) setErr(j.error||'API 오류'); setData(j); }catch(e:any){ setErr(String(e?.message||e)); } finally{ setLoading(false); }}
 useEffect(()=>{load()},[month]);
 const employees:Row[]=data.employees||[]; const leave:Row[]=data.leave||data.holidays||[]; const health:Row[]=data.health||[]; const incentives:Row[]=data.incentives||[]; const staffing:Row[]=data.staffing||[];
 const active=employees.filter(isActive); const today=new Date().toISOString().slice(0,10); const todayOff=leave.filter(r=>dateOnly(val(r,['날짜','일자','휴무일','입력일'])).startsWith(today));
 return <main><div className="top"><div><h1 style={{margin:'0 0 6px'}}>안다미로 직원관리</h1><div className="muted">MASTER_DB V6 실데이터 연결</div></div><div className="row"><input className="input" type="month" value={month} onChange={e=>setMonth(e.target.value)}/><button className="btn" onClick={load}>새로고침</button></div></div>
 <div className="cards"><Stat t="재직 직원" v={active.length}/><Stat t="오늘 휴무" v={todayOff.length}/><Stat t="오늘 근무" v={Math.max(active.length-todayOff.length,0)}/><Stat t="보건증 관리" v={health.length}/><Stat t="인센티브 데이터" v={incentives.length}/></div>
 <div className="nav">{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>{loading&&<div className="card">불러오는 중...</div>}{err&&<div className="card err">오류: {err}</div>}
 {!loading&&!err&&<>{tab==='대시보드'&&<Dashboard data={data} active={active} todayOff={todayOff} staffing={staffing}/>} {tab==='직원관리'&&<Employees rows={employees}/>} {tab==='휴무관리'&&<Leave rows={leave} employees={employees}/>} {tab==='근무인원'&&<Table title="근무인원" rows={staffing}/>} {tab==='보건증'&&<Table title="보건증현황" rows={health}/>} {tab==='인센티브'&&<Table title="인센티브요약" rows={incentives}/>} {tab==='연결확인'&&<Debug data={data}/>}</>}
 </main> }
function Stat({t,v}:{t:string,v:any}){ return <div className="card"><div className="muted">{t}</div><div className="num">{v}</div></div> }
function Dashboard({data,active,todayOff,staffing}:any){ return <div className="grid2"><div className="card"><h2>오늘 현황</h2><p>오늘 휴무자: {todayOff.length?todayOff.map((r:Row)=>nameOf(r)||val(r,['이름','직원명'])).join(', '):'없음'}</p><p>재직 직원 {active.length}명 기준으로 표시합니다.</p><p className="muted small">API 버전: {data.version||'-'} / 시트: {data.spreadsheet||'-'}</p></div><div className="card"><h2>시트 연결상태</h2>{data.sheets&&Object.entries(data.sheets).map(([k,v]:any)=><div key={k}>{v?'✅':'❌'} {k}</div>)}</div><Table title="근무인원 미리보기" rows={(staffing||[]).slice(0,8)}/></div> }
function Employees({rows}:{rows:Row[]}){ return <><div className="card"><h2>직원 목록</h2><p className="muted">MASTER_DB 직원관리 시트에서 읽어옵니다.</p></div><Table title="직원관리" rows={rows}/></> }
function Leave({rows,employees}:{rows:Row[],employees:Row[]}){ return <><div className="card"><h2>휴무 관리</h2><p className="muted">현재는 조회 단계입니다. 저장 기능은 다음 단계에서 붙입니다.</p><div className="row"><select className="grow"><option>직원 선택</option>{employees.map((r,i)=><option key={i}>{nameOf(r)}</option>)}</select><input className="input" type="date"/><select><option>휴무</option><option>반차</option><option>연차</option></select><button className="btn secondary" disabled>저장 준비중</button></div></div><Table title="휴무입력" rows={rows}/></> }
function Table({title,rows}:{title:string,rows:Row[]}){ if(!rows?.length) return <div className="card"><h2>{title}</h2><p className="muted">표시할 데이터가 없습니다.</p></div>; const keys=Object.keys(rows[0]).slice(0,10); return <div className="card" style={{overflowX:'auto'}}><h2>{title}</h2><table><thead><tr>{keys.map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.slice(0,80).map((r,i)=><tr key={i}>{keys.map(k=><td key={k}>{String(r[k]??'')}</td>)}</tr>)}</tbody></table></div> }
function Debug({data}:{data:Row}){ return <div className="card"><h2>연결 확인</h2><pre style={{whiteSpace:'pre-wrap',fontSize:12}}>{JSON.stringify(data,null,2).slice(0,12000)}</pre></div> }
