'use client';
import {useEffect,useMemo,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'';
async function api(action:string, body?:any){
  if(!API) throw new Error('NEXT_PUBLIC_API_URL이 없습니다.');
  if(body){
    const res=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...body})});
    return res.json();
  }
  const res=await fetch(`${API}?action=${encodeURIComponent(action)}`,{cache:'no-store'});
  return res.json();
}
function pick(o:any, keys:string[]){for(const k of keys){if(o&&o[k]!==undefined&&o[k]!==null&&o[k]!=='')return o[k]} return ''}
export default function Page(){
 const [tab,setTab]=useState('dashboard'); const [data,setData]=useState<any>({}); const [loading,setLoading]=useState(true); const [msg,setMsg]=useState(''); const [err,setErr]=useState('');
 const load=async()=>{setLoading(true);setErr('');try{const d=await api('all');setData(d)}catch(e:any){setErr(e.message||'불러오기 실패')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const employees=data.employees||data.staff||[]; const dashboard=data.dashboard||{}; const holidays=data.holidays||data.leave||[]; const health=data.health||[]; const incentives=data.incentives||[]; const staffing=data.staffing||[];
 const active=employees.filter((r:any)=>String(pick(r,['상태','status'])).includes('사용')||String(pick(r,['상태','status'])).includes('재직')).length || employees.length;
 const offToday=useMemo(()=>{const t=new Date(); const m=t.getMonth()+1, d=t.getDate(); return holidays.filter((r:any)=>String(pick(r,['날짜','일자','휴무일'])).includes(`${m}`)&&String(pick(r,['날짜','일자','휴무일'])).includes(`${d}`));},[holidays]);
 const saveLeave=async(e:any)=>{e.preventDefault(); setMsg(''); setErr(''); const f=new FormData(e.currentTarget); try{const r=await api('saveLeave',{date:f.get('date'),name:f.get('name'),type:f.get('type'),memo:f.get('memo')}); if(r.error)throw new Error(r.error); setMsg('휴무 입력 저장 완료'); e.currentTarget.reset(); load();}catch(x:any){setErr(x.message)}};
 const saveEmployee=async(e:any)=>{e.preventDefault(); setMsg(''); setErr(''); const f=new FormData(e.currentTarget); try{const r=await api('saveEmployee',{name:f.get('name'),position:f.get('position'),dept:f.get('dept'),status:f.get('status')}); if(r.error)throw new Error(r.error); setMsg('직원 정보 저장 완료'); e.currentTarget.reset(); load();}catch(x:any){setErr(x.message)}};
 return <main className="wrap"><div className="top"><div className="title"><h1>안다미로 직원관리</h1><p>MASTER_DB V6 연동 홈페이지</p></div><button className="btn" onClick={load}>새로고침</button></div>{err&&<div className="msg err">{err}</div>}{msg&&<div className="msg">{msg}</div>}{loading?<div className="card">불러오는 중...</div>:<><div className="grid"><div className="card"><h3>재직 직원</h3><div className="num">{pick(dashboard,['재직 직원','재직직원'])||active}</div></div><div className="card"><h3>오늘 휴무</h3><div className="num">{offToday.length}</div></div><div className="card"><h3>인센티브 데이터</h3><div className="num">{incentives.length}</div></div><div className="card"><h3>보건증 관리</h3><div className="num">{health.length}</div></div></div><div className="tabs">{['dashboard','employees','leave','health','incentive','staffing'].map(t=><button key={t} className={tab===t?'':'off'} onClick={()=>setTab(t)}>{({dashboard:'대시보드',employees:'직원관리',leave:'휴무관리',health:'보건증',incentive:'인센티브',staffing:'근무인원'} as any)[t]}</button>)}</div><section className="section">{tab==='dashboard'&&<div className="card"><h2>오늘 현황</h2><p>오늘 휴무자: {offToday.map((r:any)=>pick(r,['이름','직원명','name'])).filter(Boolean).join(', ')||'없음'}</p><p className="small">구글시트 MASTER_DB를 기준으로 표시합니다.</p></div>}{tab==='employees'&&<><div className="card"><h2>직원 추가/수정</h2><form className="form" onSubmit={saveEmployee}><input name="name" placeholder="이름" required/><input name="position" placeholder="직급"/><input name="dept" placeholder="부서"/><select name="status"><option>사용가능</option><option>제외</option><option>퇴사</option></select><button className="btn">저장</button></form></div><Table rows={employees}/></>}{tab==='leave'&&<><div className="card"><h2>휴무 입력</h2><form className="form" onSubmit={saveLeave}><input name="date" type="date" required/><input name="name" placeholder="직원명" required/><select name="type"><option>휴무</option><option>연차</option><option>반차</option><option>공휴일</option></select><input name="memo" placeholder="메모"/><button className="btn">저장</button></form></div><Table rows={holidays}/></>}{tab==='health'&&<Table rows={health}/>} {tab==='incentive'&&<Table rows={incentives}/>} {tab==='staffing'&&<Table rows={staffing}/>}</section></>}</main>}
function Table({rows}:{rows:any[]}){ if(!rows||!rows.length)return <div className="card">표시할 데이터가 없습니다.</div>; const keys=Object.keys(rows[0]).slice(0,8); return <div className="card"><table className="table"><thead><tr>{keys.map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.slice(0,200).map((r,i)=><tr key={i}>{keys.map(k=><td key={k}>{String(r[k]??'')}</td>)}</tr>)}</tbody></table></div>}
